version: "3.8"
services:
  frontend:
    env_file: .env
    # build: ../fe/
    restart: unless-stopped
    container_name: frontend
    ports:
      - 3000:3000
    networks:
      - network
    depends_on:
      backend:
        condition: service_healthy
      notifications:
        condition: service_started
  backend:
    env_file: .env
    # build: .
    restart: unless-stopped
    container_name: backend
    ports:
      - 8000:8000
    networks:
      - network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8000/api/monitor || exit 1
      interval: 5s
      timeout: 10s
      retries: 10
networks:
  network:
    driver: bridge
