name: CD
on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: relekang/python-semantic-release@v7.34.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
